-- MySQL Script generated by MySQL Workbench
-- Sat Dec 14 19:23:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema curbspringsdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `curbspringsdb` ;

-- -----------------------------------------------------
-- Schema curbspringsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `curbspringsdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `curbspringsdb` ;

-- -----------------------------------------------------
-- Table `curbspringsdb`.`coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curbspringsdb`.`coupon` (
  `code` VARCHAR(50) NOT NULL,
  `discount_amount` DECIMAL(4,2) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `curbspringsdb`.`spotowner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curbspringsdb`.`spotowner` (
  `spot_owner_id` INT NOT NULL,
  `spot_owner_name_surname` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `hash_password` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`spot_owner_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `curbspringsdb`.`parkingspot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curbspringsdb`.`parkingspot` (
  `spot_id` INT NOT NULL,
  `spot_owner_id` INT NULL DEFAULT NULL,
  `address` VARCHAR(35) NULL DEFAULT NULL,
  `type` ENUM('Open', 'Garage', 'Underground') NULL DEFAULT NULL,
  `has_charger` TINYINT(1) NULL DEFAULT NULL,
  `available` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`spot_id`),
  INDEX `spot_owner_id` (`spot_owner_id` ASC) VISIBLE,
  CONSTRAINT `parkingspot_ibfk_1`
    FOREIGN KEY (`spot_owner_id`)
    REFERENCES `curbspringsdb`.`spotowner` (`spot_owner_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `curbspringsdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curbspringsdb`.`user` (
  `user_id` INT NOT NULL,
  `user_name_surname` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `hash_password` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `curbspringsdb`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curbspringsdb`.`payment` (
  `payment_id` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `amount` DECIMAL(10,2) NULL DEFAULT NULL,
  `payment_method` ENUM('DebitCard', 'CreditCard', 'GooglePay', 'ApplePay') NULL DEFAULT NULL,
  `payment_status` ENUM('Pending', 'Completed', 'Failed') NULL DEFAULT NULL,
  `transaction_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `payment_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `curbspringsdb`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `curbspringsdb`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curbspringsdb`.`vehicle` (
  `license_plate` VARCHAR(7) NOT NULL,
  `vehicle_type` ENUM('Car', 'Truck', 'Motorcycle') NULL DEFAULT NULL,
  PRIMARY KEY (`license_plate`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `curbspringsdb`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curbspringsdb`.`reservation` (
  `reservation_id` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `spot_id` INT NULL DEFAULT NULL,
  `license_plate` VARCHAR(7) NULL DEFAULT NULL,
  `start_time` DATETIME NULL DEFAULT NULL,
  `end_time` DATETIME NULL DEFAULT NULL,
  `status` ENUM('Reserved', 'Cancelled', 'Completed') NULL DEFAULT NULL,
  PRIMARY KEY (`reservation_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `spot_id` (`spot_id` ASC) VISIBLE,
  INDEX `license_plate` (`license_plate` ASC) VISIBLE,
  CONSTRAINT `reservation_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `curbspringsdb`.`user` (`user_id`),
  CONSTRAINT `reservation_ibfk_2`
    FOREIGN KEY (`spot_id`)
    REFERENCES `curbspringsdb`.`parkingspot` (`spot_id`),
  CONSTRAINT `reservation_ibfk_3`
    FOREIGN KEY (`license_plate`)
    REFERENCES `curbspringsdb`.`vehicle` (`license_plate`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `curbspringsdb`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curbspringsdb`.`review` (
  `review_id` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `spot_id` INT NULL DEFAULT NULL,
  `rating` ENUM('1', '2', '3', '4', '5') NULL DEFAULT NULL,
  `review_text` TEXT NULL DEFAULT NULL,
  `review_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `spot_id` (`spot_id` ASC) VISIBLE,
  CONSTRAINT `review_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `curbspringsdb`.`user` (`user_id`),
  CONSTRAINT `review_ibfk_2`
    FOREIGN KEY (`spot_id`)
    REFERENCES `curbspringsdb`.`parkingspot` (`spot_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `curbspringsdb`.`user_has_coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curbspringsdb`.`user_has_coupon` (
  `user_id` INT NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`user_id`, `code`),
  INDEX `code` (`code` ASC) VISIBLE,
  CONSTRAINT `user_has_coupon_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `curbspringsdb`.`user` (`user_id`),
  CONSTRAINT `user_has_coupon_ibfk_2`
    FOREIGN KEY (`code`)
    REFERENCES `curbspringsdb`.`coupon` (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `curbspringsdb`.`user_owns_vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curbspringsdb`.`user_owns_vehicle` (
  `user_id` INT NOT NULL,
  `license_plate` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`user_id`, `license_plate`),
  INDEX `license_plate` (`license_plate` ASC) VISIBLE,
  CONSTRAINT `user_owns_vehicle_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `curbspringsdb`.`user` (`user_id`),
  CONSTRAINT `user_owns_vehicle_ibfk_2`
    FOREIGN KEY (`license_plate`)
    REFERENCES `curbspringsdb`.`vehicle` (`license_plate`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
